### ISSUE TITLE
iphone-arm teleoperation

### ISSUE THREAD

**Issue by s140335** [j96w/MimicPlay#7]
Hi, 
Here https://mimic-play.github.io/ it seems you are using an iPhone to control the robotic arm. Could you please let me know how you did so? Is there any APP or open-source code to do so? Thanks.

**Comment by j96w** [comment]
Hi, yes, we are using RoboTurk (https://roboturk.stanford.edu/) to teleoperate the robot with an iPhone. However, RoboTurk has not been open-sourced since the leading student of RoboTurk graduated. Feel free to use your teleoperation interface or try out the spacemouse as introduced [here](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/scripts/collect_human_demonstrations.py).

**Comment by j96w** [comment]
Since it is not related to this repo, closing for now.
